// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tokenization/v22/address_lists.proto

package v22

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// An AddressList is a list of addresses that are referenced by an ID.
// AddressLists are used in defining approvals ia a reusbale identifier.
// Note: We also support a reserved ID system by string ID; "Mint", "!Mint"
type AddressList struct {
	// Unique identifier for the address list.
	ListId string `protobuf:"bytes,1,opt,name=listId,proto3" json:"listId,omitempty"`
	// List of addresses included in the list.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Indicates whether the list includes the specified addresses (true) or excludes them (false).
	Whitelist bool `protobuf:"varint,3,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
	// URI (Uniform Resource Identifier) associated with the address list to provide metadata, if applicable.
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// Custom arbitrary data or additional information related to the address list.
	CustomData string `protobuf:"bytes,5,opt,name=customData,proto3" json:"customData,omitempty"`
	// The user or entity who created the address list.
	CreatedBy string `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
}

func (m *AddressList) Reset()         { *m = AddressList{} }
func (m *AddressList) String() string { return proto.CompactTextString(m) }
func (*AddressList) ProtoMessage()    {}
func (*AddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f9cfaf99fb743c, []int{0}
}
func (m *AddressList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressList.Merge(m, src)
}
func (m *AddressList) XXX_Size() int {
	return m.Size()
}
func (m *AddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressList.DiscardUnknown(m)
}

var xxx_messageInfo_AddressList proto.InternalMessageInfo

func (m *AddressList) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *AddressList) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *AddressList) GetWhitelist() bool {
	if m != nil {
		return m.Whitelist
	}
	return false
}

func (m *AddressList) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *AddressList) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func (m *AddressList) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

// AddressListInput is used for creating address lists via MsgCreateAddressLists.
// It contains all fields from AddressList except createdBy, which is automatically set from the message creator.
type AddressListInput struct {
	// Unique identifier for the address list.
	ListId string `protobuf:"bytes,1,opt,name=listId,proto3" json:"listId,omitempty"`
	// List of addresses included in the list.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Indicates whether the list includes the specified addresses (true) or excludes them (false).
	Whitelist bool `protobuf:"varint,3,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
	// URI (Uniform Resource Identifier) associated with the address list to provide metadata, if applicable.
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// Custom arbitrary data or additional information related to the address list.
	CustomData string `protobuf:"bytes,5,opt,name=customData,proto3" json:"customData,omitempty"`
}

func (m *AddressListInput) Reset()         { *m = AddressListInput{} }
func (m *AddressListInput) String() string { return proto.CompactTextString(m) }
func (*AddressListInput) ProtoMessage()    {}
func (*AddressListInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f9cfaf99fb743c, []int{1}
}
func (m *AddressListInput) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressListInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressListInput.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressListInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressListInput.Merge(m, src)
}
func (m *AddressListInput) XXX_Size() int {
	return m.Size()
}
func (m *AddressListInput) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressListInput.DiscardUnknown(m)
}

var xxx_messageInfo_AddressListInput proto.InternalMessageInfo

func (m *AddressListInput) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *AddressListInput) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *AddressListInput) GetWhitelist() bool {
	if m != nil {
		return m.Whitelist
	}
	return false
}

func (m *AddressListInput) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *AddressListInput) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressList)(nil), "tokenization.v22.AddressList")
	proto.RegisterType((*AddressListInput)(nil), "tokenization.v22.AddressListInput")
}

func init() {
	proto.RegisterFile("tokenization/v22/address_lists.proto", fileDescriptor_b0f9cfaf99fb743c)
}

var fileDescriptor_b0f9cfaf99fb743c = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x51, 0xb1, 0x4a, 0xc4, 0x40,
	0x14, 0xbc, 0xf5, 0x34, 0x98, 0xb5, 0x09, 0x41, 0x64, 0x39, 0x64, 0x0d, 0x87, 0x45, 0xaa, 0x2c,
	0xc4, 0xd6, 0xc6, 0xc3, 0xe6, 0xc0, 0x2a, 0x85, 0x85, 0x8d, 0x6c, 0x92, 0x25, 0x59, 0xbc, 0xcb,
	0x86, 0xec, 0xcb, 0xe9, 0xf9, 0x15, 0x96, 0xfe, 0x86, 0x7f, 0x61, 0x79, 0xa5, 0xa5, 0x24, 0x3f,
	0x22, 0x9b, 0x0b, 0x24, 0xe2, 0x0f, 0xd8, 0xcd, 0x9b, 0x19, 0xe6, 0x0d, 0x0c, 0xbe, 0x04, 0xf5,
	0x24, 0x0a, 0xf9, 0xca, 0x41, 0xaa, 0x82, 0x6d, 0xc2, 0x90, 0xf1, 0x34, 0xad, 0x84, 0xd6, 0x8f,
	0x2b, 0xa9, 0x41, 0x07, 0x65, 0xa5, 0x40, 0xb9, 0xce, 0xd8, 0x15, 0x6c, 0xc2, 0x70, 0x76, 0x9a,
	0xa9, 0x4c, 0x75, 0x22, 0x33, 0x68, 0xef, 0x9b, 0x5d, 0xfc, 0x49, 0x8b, 0xf9, 0x8a, 0x17, 0x89,
	0xe8, 0x83, 0xe6, 0x1f, 0x08, 0x9f, 0xdc, 0xec, 0x1f, 0xdc, 0x49, 0x0d, 0xee, 0x19, 0xb6, 0xcc,
	0x9f, 0x65, 0x4a, 0x90, 0x87, 0x7c, 0x3b, 0xea, 0x2f, 0xf7, 0x1c, 0xdb, 0x7d, 0x0f, 0xa1, 0xc9,
	0x81, 0x37, 0xf5, 0xed, 0x68, 0x20, 0x8c, 0xfa, 0x9c, 0x4b, 0x10, 0xc6, 0x4c, 0xa6, 0x1e, 0xf2,
	0x8f, 0xa3, 0x81, 0x70, 0x1d, 0x3c, 0xad, 0x2b, 0x49, 0x0e, 0xbb, 0x40, 0x03, 0x5d, 0x8a, 0x71,
	0x52, 0x6b, 0x50, 0xeb, 0x5b, 0x0e, 0x9c, 0x1c, 0x75, 0xc2, 0x88, 0x31, 0x79, 0x49, 0x25, 0x38,
	0x88, 0x74, 0xb1, 0x25, 0x56, 0x27, 0x0f, 0xc4, 0xfc, 0x1d, 0x61, 0x67, 0xd4, 0x79, 0x59, 0x94,
	0xf5, 0x3f, 0x29, 0xbe, 0xb8, 0xff, 0x6c, 0x28, 0xda, 0x35, 0x14, 0x7d, 0x37, 0x14, 0xbd, 0xb5,
	0x74, 0xb2, 0x6b, 0xe9, 0xe4, 0xab, 0xa5, 0x93, 0x87, 0xeb, 0x4c, 0x42, 0x5e, 0xc7, 0x41, 0xa2,
	0xd6, 0x2c, 0x96, 0x10, 0xf3, 0x34, 0x13, 0x7a, 0x40, 0x49, 0xce, 0x65, 0xc1, 0x5e, 0xd8, 0xaf,
	0xbd, 0x60, 0x5b, 0x0a, 0x6d, 0x56, 0x8b, 0xad, 0x6e, 0xad, 0xab, 0x9f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x55, 0x9f, 0x88, 0xfb, 0x1e, 0x02, 0x00, 0x00,
}

func (m *AddressList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CustomData) > 0 {
		i -= len(m.CustomData)
		copy(dAtA[i:], m.CustomData)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.CustomData)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if m.Whitelist {
		i--
		if m.Whitelist {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ListId) > 0 {
		i -= len(m.ListId)
		copy(dAtA[i:], m.ListId)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.ListId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AddressListInput) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressListInput) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressListInput) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CustomData) > 0 {
		i -= len(m.CustomData)
		copy(dAtA[i:], m.CustomData)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.CustomData)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if m.Whitelist {
		i--
		if m.Whitelist {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ListId) > 0 {
		i -= len(m.ListId)
		copy(dAtA[i:], m.ListId)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.ListId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAddressLists(dAtA []byte, offset int, v uint64) int {
	offset -= sovAddressLists(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddressList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ListId)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovAddressLists(uint64(l))
		}
	}
	if m.Whitelist {
		n += 2
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.CustomData)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	return n
}

func (m *AddressListInput) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ListId)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovAddressLists(uint64(l))
		}
	}
	if m.Whitelist {
		n += 2
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.CustomData)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	return n
}

func sovAddressLists(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAddressLists(x uint64) (n int) {
	return sovAddressLists(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddressList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAddressLists
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Whitelist = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAddressLists(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAddressLists
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddressListInput) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAddressLists
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressListInput: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressListInput: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Whitelist = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAddressLists(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAddressLists
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAddressLists(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAddressLists
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAddressLists
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAddressLists
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAddressLists
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAddressLists        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAddressLists          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAddressLists = fmt.Errorf("proto: unexpected end of group")
)
