// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package gammv1beta1

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_PoolRecordWithCFMMLink                       protoreflect.MessageDescriptor
	fd_PoolRecordWithCFMMLink_denom0                protoreflect.FieldDescriptor
	fd_PoolRecordWithCFMMLink_denom1                protoreflect.FieldDescriptor
	fd_PoolRecordWithCFMMLink_tick_spacing          protoreflect.FieldDescriptor
	fd_PoolRecordWithCFMMLink_exponent_at_price_one protoreflect.FieldDescriptor
	fd_PoolRecordWithCFMMLink_spread_factor         protoreflect.FieldDescriptor
	fd_PoolRecordWithCFMMLink_balancer_pool_id      protoreflect.FieldDescriptor
)

func init() {
	file_gamm_v1beta1_gov_proto_init()
	md_PoolRecordWithCFMMLink = File_gamm_v1beta1_gov_proto.Messages().ByName("PoolRecordWithCFMMLink")
	fd_PoolRecordWithCFMMLink_denom0 = md_PoolRecordWithCFMMLink.Fields().ByName("denom0")
	fd_PoolRecordWithCFMMLink_denom1 = md_PoolRecordWithCFMMLink.Fields().ByName("denom1")
	fd_PoolRecordWithCFMMLink_tick_spacing = md_PoolRecordWithCFMMLink.Fields().ByName("tick_spacing")
	fd_PoolRecordWithCFMMLink_exponent_at_price_one = md_PoolRecordWithCFMMLink.Fields().ByName("exponent_at_price_one")
	fd_PoolRecordWithCFMMLink_spread_factor = md_PoolRecordWithCFMMLink.Fields().ByName("spread_factor")
	fd_PoolRecordWithCFMMLink_balancer_pool_id = md_PoolRecordWithCFMMLink.Fields().ByName("balancer_pool_id")
}

var _ protoreflect.Message = (*fastReflection_PoolRecordWithCFMMLink)(nil)

type fastReflection_PoolRecordWithCFMMLink PoolRecordWithCFMMLink

func (x *PoolRecordWithCFMMLink) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PoolRecordWithCFMMLink)(x)
}

func (x *PoolRecordWithCFMMLink) slowProtoReflect() protoreflect.Message {
	mi := &file_gamm_v1beta1_gov_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PoolRecordWithCFMMLink_messageType fastReflection_PoolRecordWithCFMMLink_messageType
var _ protoreflect.MessageType = fastReflection_PoolRecordWithCFMMLink_messageType{}

type fastReflection_PoolRecordWithCFMMLink_messageType struct{}

func (x fastReflection_PoolRecordWithCFMMLink_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PoolRecordWithCFMMLink)(nil)
}
func (x fastReflection_PoolRecordWithCFMMLink_messageType) New() protoreflect.Message {
	return new(fastReflection_PoolRecordWithCFMMLink)
}
func (x fastReflection_PoolRecordWithCFMMLink_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PoolRecordWithCFMMLink
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PoolRecordWithCFMMLink) Descriptor() protoreflect.MessageDescriptor {
	return md_PoolRecordWithCFMMLink
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PoolRecordWithCFMMLink) Type() protoreflect.MessageType {
	return _fastReflection_PoolRecordWithCFMMLink_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PoolRecordWithCFMMLink) New() protoreflect.Message {
	return new(fastReflection_PoolRecordWithCFMMLink)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PoolRecordWithCFMMLink) Interface() protoreflect.ProtoMessage {
	return (*PoolRecordWithCFMMLink)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PoolRecordWithCFMMLink) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Denom0 != "" {
		value := protoreflect.ValueOfString(x.Denom0)
		if !f(fd_PoolRecordWithCFMMLink_denom0, value) {
			return
		}
	}
	if x.Denom1 != "" {
		value := protoreflect.ValueOfString(x.Denom1)
		if !f(fd_PoolRecordWithCFMMLink_denom1, value) {
			return
		}
	}
	if x.TickSpacing != uint64(0) {
		value := protoreflect.ValueOfUint64(x.TickSpacing)
		if !f(fd_PoolRecordWithCFMMLink_tick_spacing, value) {
			return
		}
	}
	if x.ExponentAtPriceOne != "" {
		value := protoreflect.ValueOfString(x.ExponentAtPriceOne)
		if !f(fd_PoolRecordWithCFMMLink_exponent_at_price_one, value) {
			return
		}
	}
	if x.SpreadFactor != "" {
		value := protoreflect.ValueOfString(x.SpreadFactor)
		if !f(fd_PoolRecordWithCFMMLink_spread_factor, value) {
			return
		}
	}
	if x.BalancerPoolId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.BalancerPoolId)
		if !f(fd_PoolRecordWithCFMMLink_balancer_pool_id, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PoolRecordWithCFMMLink) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		return x.Denom0 != ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		return x.Denom1 != ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		return x.TickSpacing != uint64(0)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		return x.ExponentAtPriceOne != ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		return x.SpreadFactor != ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		return x.BalancerPoolId != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoolRecordWithCFMMLink) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		x.Denom0 = ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		x.Denom1 = ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		x.TickSpacing = uint64(0)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		x.ExponentAtPriceOne = ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		x.SpreadFactor = ""
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		x.BalancerPoolId = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PoolRecordWithCFMMLink) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		value := x.Denom0
		return protoreflect.ValueOfString(value)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		value := x.Denom1
		return protoreflect.ValueOfString(value)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		value := x.TickSpacing
		return protoreflect.ValueOfUint64(value)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		value := x.ExponentAtPriceOne
		return protoreflect.ValueOfString(value)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		value := x.SpreadFactor
		return protoreflect.ValueOfString(value)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		value := x.BalancerPoolId
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoolRecordWithCFMMLink) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		x.Denom0 = value.Interface().(string)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		x.Denom1 = value.Interface().(string)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		x.TickSpacing = value.Uint()
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		x.ExponentAtPriceOne = value.Interface().(string)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		x.SpreadFactor = value.Interface().(string)
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		x.BalancerPoolId = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoolRecordWithCFMMLink) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		panic(fmt.Errorf("field denom0 of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		panic(fmt.Errorf("field denom1 of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		panic(fmt.Errorf("field tick_spacing of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		panic(fmt.Errorf("field exponent_at_price_one of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		panic(fmt.Errorf("field spread_factor of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		panic(fmt.Errorf("field balancer_pool_id of message gamm.v1beta1.PoolRecordWithCFMMLink is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PoolRecordWithCFMMLink) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom0":
		return protoreflect.ValueOfString("")
	case "gamm.v1beta1.PoolRecordWithCFMMLink.denom1":
		return protoreflect.ValueOfString("")
	case "gamm.v1beta1.PoolRecordWithCFMMLink.tick_spacing":
		return protoreflect.ValueOfUint64(uint64(0))
	case "gamm.v1beta1.PoolRecordWithCFMMLink.exponent_at_price_one":
		return protoreflect.ValueOfString("")
	case "gamm.v1beta1.PoolRecordWithCFMMLink.spread_factor":
		return protoreflect.ValueOfString("")
	case "gamm.v1beta1.PoolRecordWithCFMMLink.balancer_pool_id":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: gamm.v1beta1.PoolRecordWithCFMMLink"))
		}
		panic(fmt.Errorf("message gamm.v1beta1.PoolRecordWithCFMMLink does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PoolRecordWithCFMMLink) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in gamm.v1beta1.PoolRecordWithCFMMLink", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PoolRecordWithCFMMLink) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PoolRecordWithCFMMLink) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PoolRecordWithCFMMLink) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PoolRecordWithCFMMLink) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PoolRecordWithCFMMLink)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.Denom0)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Denom1)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.TickSpacing != 0 {
			n += 1 + runtime.Sov(uint64(x.TickSpacing))
		}
		l = len(x.ExponentAtPriceOne)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SpreadFactor)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.BalancerPoolId != 0 {
			n += 1 + runtime.Sov(uint64(x.BalancerPoolId))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PoolRecordWithCFMMLink)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.BalancerPoolId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.BalancerPoolId))
			i--
			dAtA[i] = 0x30
		}
		if len(x.SpreadFactor) > 0 {
			i -= len(x.SpreadFactor)
			copy(dAtA[i:], x.SpreadFactor)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SpreadFactor)))
			i--
			dAtA[i] = 0x2a
		}
		if len(x.ExponentAtPriceOne) > 0 {
			i -= len(x.ExponentAtPriceOne)
			copy(dAtA[i:], x.ExponentAtPriceOne)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ExponentAtPriceOne)))
			i--
			dAtA[i] = 0x22
		}
		if x.TickSpacing != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.TickSpacing))
			i--
			dAtA[i] = 0x18
		}
		if len(x.Denom1) > 0 {
			i -= len(x.Denom1)
			copy(dAtA[i:], x.Denom1)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom1)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.Denom0) > 0 {
			i -= len(x.Denom0)
			copy(dAtA[i:], x.Denom0)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Denom0)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PoolRecordWithCFMMLink)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoolRecordWithCFMMLink: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PoolRecordWithCFMMLink: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom0", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom0 = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Denom1", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Denom1 = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field TickSpacing", wireType)
				}
				x.TickSpacing = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.TickSpacing |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ExponentAtPriceOne", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ExponentAtPriceOne = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 5:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SpreadFactor", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SpreadFactor = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 6:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field BalancerPoolId", wireType)
				}
				x.BalancerPoolId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.BalancerPoolId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: gamm/v1beta1/gov.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PoolRecordWithCFMMLink struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Denom0             string `protobuf:"bytes,1,opt,name=denom0,proto3" json:"denom0,omitempty"`
	Denom1             string `protobuf:"bytes,2,opt,name=denom1,proto3" json:"denom1,omitempty"`
	TickSpacing        uint64 `protobuf:"varint,3,opt,name=tick_spacing,json=tickSpacing,proto3" json:"tick_spacing,omitempty"`
	ExponentAtPriceOne string `protobuf:"bytes,4,opt,name=exponent_at_price_one,json=exponentAtPriceOne,proto3" json:"exponent_at_price_one,omitempty"`
	SpreadFactor       string `protobuf:"bytes,5,opt,name=spread_factor,json=spreadFactor,proto3" json:"spread_factor,omitempty"`
	BalancerPoolId     uint64 `protobuf:"varint,6,opt,name=balancer_pool_id,json=balancerPoolId,proto3" json:"balancer_pool_id,omitempty"`
}

func (x *PoolRecordWithCFMMLink) Reset() {
	*x = PoolRecordWithCFMMLink{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gamm_v1beta1_gov_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PoolRecordWithCFMMLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolRecordWithCFMMLink) ProtoMessage() {}

// Deprecated: Use PoolRecordWithCFMMLink.ProtoReflect.Descriptor instead.
func (*PoolRecordWithCFMMLink) Descriptor() ([]byte, []int) {
	return file_gamm_v1beta1_gov_proto_rawDescGZIP(), []int{0}
}

func (x *PoolRecordWithCFMMLink) GetDenom0() string {
	if x != nil {
		return x.Denom0
	}
	return ""
}

func (x *PoolRecordWithCFMMLink) GetDenom1() string {
	if x != nil {
		return x.Denom1
	}
	return ""
}

func (x *PoolRecordWithCFMMLink) GetTickSpacing() uint64 {
	if x != nil {
		return x.TickSpacing
	}
	return 0
}

func (x *PoolRecordWithCFMMLink) GetExponentAtPriceOne() string {
	if x != nil {
		return x.ExponentAtPriceOne
	}
	return ""
}

func (x *PoolRecordWithCFMMLink) GetSpreadFactor() string {
	if x != nil {
		return x.SpreadFactor
	}
	return ""
}

func (x *PoolRecordWithCFMMLink) GetBalancerPoolId() uint64 {
	if x != nil {
		return x.BalancerPoolId
	}
	return 0
}

var File_gamm_v1beta1_gov_proto protoreflect.FileDescriptor

var file_gamm_v1beta1_gov_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x61, 0x6d, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x67,
	0x6f, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x67, 0x61, 0x6d, 0x6d, 0x2e, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x67, 0x61,
	0x6d, 0x6d, 0x2f, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x2f, 0x67, 0x65, 0x6e, 0x65, 0x73,
	0x69, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x19, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcb, 0x03, 0x0a, 0x16, 0x50, 0x6f, 0x6f, 0x6c, 0x52,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x57, 0x69, 0x74, 0x68, 0x43, 0x46, 0x4d, 0x4d, 0x4c, 0x69, 0x6e,
	0x6b, 0x12, 0x29, 0x0a, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x30, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x11, 0xf2, 0xde, 0x1f, 0x0d, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x64, 0x65, 0x6e,
	0x6f, 0x6d, 0x30, 0x22, 0x52, 0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x30, 0x12, 0x29, 0x0a, 0x06,
	0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x11, 0xf2, 0xde,
	0x1f, 0x0d, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x31, 0x22, 0x52,
	0x06, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x31, 0x12, 0x3a, 0x0a, 0x0c, 0x74, 0x69, 0x63, 0x6b, 0x5f,
	0x73, 0x70, 0x61, 0x63, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x42, 0x17, 0xf2,
	0xde, 0x1f, 0x13, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x74, 0x69, 0x63, 0x6b, 0x5f, 0x73, 0x70,
	0x61, 0x63, 0x69, 0x6e, 0x67, 0x22, 0x52, 0x0b, 0x74, 0x69, 0x63, 0x6b, 0x53, 0x70, 0x61, 0x63,
	0x69, 0x6e, 0x67, 0x12, 0x70, 0x0a, 0x15, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x5f,
	0x61, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x6e, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x42, 0x3d, 0xc8, 0xde, 0x1f, 0x00, 0xda, 0xde, 0x1f, 0x15, 0x63, 0x6f, 0x73, 0x6d,
	0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x49, 0x6e,
	0x74, 0xf2, 0xde, 0x1f, 0x1c, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x65, 0x78, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x6f, 0x6e, 0x65,
	0x22, 0x52, 0x12, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x50, 0x72, 0x69,
	0x63, 0x65, 0x4f, 0x6e, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x73, 0x70, 0x72, 0x65, 0x61, 0x64, 0x5f,
	0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x42, 0x3b, 0xc8, 0xde,
	0x1f, 0x00, 0xda, 0xde, 0x1f, 0x1b, 0x63, 0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e,
	0x69, 0x6f, 0x2f, 0x6d, 0x61, 0x74, 0x68, 0x2e, 0x4c, 0x65, 0x67, 0x61, 0x63, 0x79, 0x44, 0x65,
	0x63, 0xf2, 0xde, 0x1f, 0x14, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x73, 0x70, 0x72, 0x65, 0x61,
	0x64, 0x5f, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x52, 0x0c, 0x73, 0x70, 0x72, 0x65, 0x61,
	0x64, 0x46, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x45, 0x0a, 0x10, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x42, 0x1b, 0xf2, 0xde, 0x1f, 0x17, 0x79, 0x61, 0x6d, 0x6c, 0x3a, 0x22, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x69, 0x64, 0x22, 0x52, 0x0e,
	0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x72, 0x50, 0x6f, 0x6f, 0x6c, 0x49, 0x64, 0x3a, 0x04,
	0xe8, 0xa0, 0x1f, 0x01, 0x42, 0x9a, 0x01, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x61, 0x6d,
	0x6d, 0x2e, 0x76, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x42, 0x08, 0x47, 0x6f, 0x76, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2b, 0x62, 0x69, 0x74, 0x62, 0x61, 0x64, 0x67, 0x65, 0x73,
	0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x61, 0x6d, 0x6d, 0x2f, 0x76,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0x3b, 0x67, 0x61, 0x6d, 0x6d, 0x76, 0x31, 0x62, 0x65, 0x74,
	0x61, 0x31, 0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x0c, 0x47, 0x61, 0x6d, 0x6d, 0x2e,
	0x56, 0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xca, 0x02, 0x0c, 0x47, 0x61, 0x6d, 0x6d, 0x5c, 0x56,
	0x31, 0x62, 0x65, 0x74, 0x61, 0x31, 0xe2, 0x02, 0x18, 0x47, 0x61, 0x6d, 0x6d, 0x5c, 0x56, 0x31,
	0x62, 0x65, 0x74, 0x61, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0d, 0x47, 0x61, 0x6d, 0x6d, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x65, 0x74, 0x61,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gamm_v1beta1_gov_proto_rawDescOnce sync.Once
	file_gamm_v1beta1_gov_proto_rawDescData = file_gamm_v1beta1_gov_proto_rawDesc
)

func file_gamm_v1beta1_gov_proto_rawDescGZIP() []byte {
	file_gamm_v1beta1_gov_proto_rawDescOnce.Do(func() {
		file_gamm_v1beta1_gov_proto_rawDescData = protoimpl.X.CompressGZIP(file_gamm_v1beta1_gov_proto_rawDescData)
	})
	return file_gamm_v1beta1_gov_proto_rawDescData
}

var file_gamm_v1beta1_gov_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gamm_v1beta1_gov_proto_goTypes = []interface{}{
	(*PoolRecordWithCFMMLink)(nil), // 0: gamm.v1beta1.PoolRecordWithCFMMLink
}
var file_gamm_v1beta1_gov_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gamm_v1beta1_gov_proto_init() }
func file_gamm_v1beta1_gov_proto_init() {
	if File_gamm_v1beta1_gov_proto != nil {
		return
	}
	file_gamm_v1beta1_genesis_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_gamm_v1beta1_gov_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PoolRecordWithCFMMLink); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gamm_v1beta1_gov_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamm_v1beta1_gov_proto_goTypes,
		DependencyIndexes: file_gamm_v1beta1_gov_proto_depIdxs,
		MessageInfos:      file_gamm_v1beta1_gov_proto_msgTypes,
	}.Build()
	File_gamm_v1beta1_gov_proto = out.File
	file_gamm_v1beta1_gov_proto_rawDesc = nil
	file_gamm_v1beta1_gov_proto_goTypes = nil
	file_gamm_v1beta1_gov_proto_depIdxs = nil
}
