// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: badges/v0/address_lists.proto

package v0

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// An AddressList is a list of addresses that are referenced by an ID.
// The list may include only the specified addresses, or it may include all addresses but
// the specified addresses (depending on if whitelist is true (whitelist) or false (blacklist)).
//
// AddressLists are used for defining approvals, as well as being a simplified badge interface.
type AddressList struct {
	// Unique identifier for the address list.
	ListId string `protobuf:"bytes,1,opt,name=listId,proto3" json:"listId,omitempty"`
	// List of addresses included in the list.
	Addresses []string `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// Indicates whether the list includes the specified addresses (true) or excludes them (false).
	Whitelist bool `protobuf:"varint,3,opt,name=whitelist,proto3" json:"whitelist,omitempty"`
	// URI (Uniform Resource Identifier) associated with the address list to provide metadata, if applicable.
	Uri string `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	// Custom arbitrary data or additional information related to the address list.
	CustomData string `protobuf:"bytes,5,opt,name=customData,proto3" json:"customData,omitempty"`
	// The user or entity who created the address list.
	CreatedBy string `protobuf:"bytes,6,opt,name=createdBy,proto3" json:"createdBy,omitempty"`
	// The alias BitBadges address for the list.
	AliasAddress string `protobuf:"bytes,7,opt,name=aliasAddress,proto3" json:"aliasAddress,omitempty"`
}

func (m *AddressList) Reset()         { *m = AddressList{} }
func (m *AddressList) String() string { return proto.CompactTextString(m) }
func (*AddressList) ProtoMessage()    {}
func (*AddressList) Descriptor() ([]byte, []int) {
	return fileDescriptor_3a9ac8a46db3d7fc, []int{0}
}
func (m *AddressList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressList.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressList.Merge(m, src)
}
func (m *AddressList) XXX_Size() int {
	return m.Size()
}
func (m *AddressList) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressList.DiscardUnknown(m)
}

var xxx_messageInfo_AddressList proto.InternalMessageInfo

func (m *AddressList) GetListId() string {
	if m != nil {
		return m.ListId
	}
	return ""
}

func (m *AddressList) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *AddressList) GetWhitelist() bool {
	if m != nil {
		return m.Whitelist
	}
	return false
}

func (m *AddressList) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *AddressList) GetCustomData() string {
	if m != nil {
		return m.CustomData
	}
	return ""
}

func (m *AddressList) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddressList) GetAliasAddress() string {
	if m != nil {
		return m.AliasAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*AddressList)(nil), "badges.v0.AddressList")
}

func init() { proto.RegisterFile("badges/v0/address_lists.proto", fileDescriptor_3a9ac8a46db3d7fc) }

var fileDescriptor_3a9ac8a46db3d7fc = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x18, 0x84, 0x1b, 0xab, 0xd5, 0x46, 0x0f, 0x12, 0x44, 0xc2, 0xa2, 0xa1, 0xec, 0xa9, 0xa7, 0x66,
	0x41, 0x7c, 0x00, 0x17, 0x2f, 0x82, 0x20, 0xf4, 0xe8, 0x45, 0xd2, 0x26, 0xb4, 0x81, 0xee, 0x66,
	0x69, 0xd2, 0xd5, 0x7d, 0x0b, 0x1f, 0xcb, 0xe3, 0x5e, 0x04, 0x8f, 0xd2, 0xbe, 0x88, 0x24, 0x0d,
	0x56, 0x6f, 0xd3, 0x6f, 0xe6, 0x9f, 0x86, 0x81, 0xd7, 0x05, 0xe3, 0x95, 0xd0, 0x74, 0xbb, 0xa0,
	0x8c, 0xf3, 0x56, 0x68, 0xfd, 0xd2, 0x48, 0x6d, 0x74, 0xb6, 0x69, 0x95, 0x51, 0x28, 0x1e, 0xed,
	0x6c, 0xbb, 0x98, 0x5d, 0x54, 0xaa, 0x52, 0x8e, 0x52, 0xab, 0xc6, 0xc0, 0x0c, 0x4f, 0xf7, 0x05,
	0x6b, 0xd8, 0xba, 0x14, 0xfe, 0x74, 0xfe, 0x09, 0xe0, 0xe9, 0xdd, 0x58, 0xf9, 0x28, 0xb5, 0x41,
	0x97, 0x30, 0xb2, 0xcd, 0x0f, 0x1c, 0x83, 0x04, 0xa4, 0x71, 0xee, 0xbf, 0xd0, 0x15, 0x8c, 0xfd,
	0x9f, 0x85, 0xc6, 0x07, 0x49, 0x98, 0xc6, 0xf9, 0x04, 0xac, 0xfb, 0x5a, 0x4b, 0x23, 0x6c, 0x18,
	0x87, 0x09, 0x48, 0x4f, 0xf2, 0x09, 0xa0, 0x73, 0x18, 0x76, 0xad, 0xc4, 0x87, 0xae, 0xd0, 0x4a,
	0x44, 0x20, 0x2c, 0x3b, 0x6d, 0xd4, 0xea, 0x9e, 0x19, 0x86, 0x8f, 0x9c, 0xf1, 0x87, 0xd8, 0xbe,
	0xb2, 0x15, 0xcc, 0x08, 0xbe, 0xdc, 0xe1, 0xc8, 0xd9, 0x13, 0x40, 0x73, 0x78, 0xc6, 0x1a, 0xc9,
	0xb4, 0x7f, 0x37, 0x3e, 0x76, 0x81, 0x7f, 0x6c, 0xf9, 0xf4, 0xd1, 0x13, 0xb0, 0xef, 0x09, 0xf8,
	0xee, 0x09, 0x78, 0x1f, 0x48, 0xb0, 0x1f, 0x48, 0xf0, 0x35, 0x90, 0xe0, 0xf9, 0xb6, 0x92, 0xa6,
	0xee, 0x8a, 0xac, 0x54, 0x2b, 0x5a, 0x48, 0xe3, 0x97, 0xf9, 0x55, 0x65, 0xcd, 0xe4, 0x9a, 0xbe,
	0x51, 0xcf, 0xcd, 0x6e, 0xe3, 0x76, 0x2b, 0x22, 0xb7, 0xd7, 0xcd, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1f, 0x93, 0x74, 0x0d, 0x8b, 0x01, 0x00, 0x00,
}

func (m *AddressList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AliasAddress) > 0 {
		i -= len(m.AliasAddress)
		copy(dAtA[i:], m.AliasAddress)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.AliasAddress)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.CustomData) > 0 {
		i -= len(m.CustomData)
		copy(dAtA[i:], m.CustomData)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.CustomData)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x22
	}
	if m.Whitelist {
		i--
		if m.Whitelist {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintAddressLists(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.ListId) > 0 {
		i -= len(m.ListId)
		copy(dAtA[i:], m.ListId)
		i = encodeVarintAddressLists(dAtA, i, uint64(len(m.ListId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAddressLists(dAtA []byte, offset int, v uint64) int {
	offset -= sovAddressLists(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddressList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ListId)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovAddressLists(uint64(l))
		}
	}
	if m.Whitelist {
		n += 2
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.CustomData)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	l = len(m.AliasAddress)
	if l > 0 {
		n += 1 + l + sovAddressLists(uint64(l))
	}
	return n
}

func sovAddressLists(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAddressLists(x uint64) (n int) {
	return sovAddressLists(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddressList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAddressLists
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ListId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Whitelist", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Whitelist = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CustomData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CustomData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AliasAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAddressLists
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAddressLists
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AliasAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAddressLists(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAddressLists
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAddressLists(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAddressLists
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAddressLists
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAddressLists
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAddressLists
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAddressLists
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAddressLists        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAddressLists          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAddressLists = fmt.Errorf("proto: unexpected end of group")
)
