package keeper

import (
	"github.com/bitbadges/bitbadgeschain/x/badges/types"

	sdkerrors "cosmossdk.io/errors"
)

var (
	ErrCollectionNotExists                      = sdkerrors.Register(types.ModuleName, 4, "collection does not exist")
	ErrForbiddenTime                            = sdkerrors.Register(types.ModuleName, 5, "this permission is forbidden at this time")
	ErrUserBalanceNotExists                     = sdkerrors.Register(types.ModuleName, 8, "user balance is empty or does not exist")
	ErrSupplyEqualsZero                         = sdkerrors.Register(types.ModuleName, 13, "can't create a token with zero supply")
	ErrSenderIsNotManager                       = sdkerrors.Register(types.ModuleName, 14, "sender of tx is not the manager of the collection. must be manager to access this privilege")
	ErrAccountCanNotEqualCreator                = sdkerrors.Register(types.ModuleName, 35, "account can not equal creator")
	ErrRootHashInvalid                          = sdkerrors.Register(types.ModuleName, 49, "root hash invalid")
	ErrDecodingHexString                        = sdkerrors.Register(types.ModuleName, 53, "couldn't decode hex string")
	ErrWrongBalancesType                        = sdkerrors.Register(types.ModuleName, 64, "wrong balances type ")
	ErrCollectionIsArchived                     = sdkerrors.Register(types.ModuleName, 67, "collection is currently archived (read-only)")
	ErrNotImplemented                           = sdkerrors.Register(types.ModuleName, 69, "not implemented")
	ErrInadequateApprovals                      = sdkerrors.Register(types.ModuleName, 71, "inadequate approvals")
	ErrInvalidAddressListId                     = sdkerrors.Register(types.ModuleName, 72, "invalid address list id")
	ErrAddressListNotFound                      = sdkerrors.Register(types.ModuleName, 73, "address list not found")
	ErrCircularDependency                       = sdkerrors.Register(types.ModuleName, 75, "circular dependency")
	ErrDisallowedTransfer                       = sdkerrors.Register(types.ModuleName, 76, "disallowed transfer")
	ErrNoValidSolutionForChallenge              = sdkerrors.Register(types.ModuleName, 77, "challenge failed")
	ErrExceedsThreshold                         = sdkerrors.Register(types.ModuleName, 78, "exceeds threshold")
	ErrCircularInheritance                      = sdkerrors.Register(types.ModuleName, 79, "circular inheritance")
	ErrAddressListAlreadyExists                 = sdkerrors.Register(types.ModuleName, 80, "address list already exists")
	ErrGlobalArchive                            = sdkerrors.Register(types.ModuleName, 81, "global halt is active")
	ErrNoMatchingChallengeForChallengeTrackerId = sdkerrors.Register(types.ModuleName, 82, "no matching challenge for challenge tracker id")
	ErrInvalidDenom                             = sdkerrors.Register(types.ModuleName, 83, "invalid denom")
	ErrOverrideTimestampNotAllowed              = sdkerrors.Register(types.ModuleName, 84, "override timestamp not allowed")
	ErrAccountNotFound                          = sdkerrors.Register(types.ModuleName, 85, "account not found")
	ErrInvalidLeafSigner                        = sdkerrors.Register(types.ModuleName, 86, "invalid leaf signer")
	ErrInvalidConversion                        = sdkerrors.Register(types.ModuleName, 87, "invalid conversion")
	ErrInvalidBalanceKeyFormat                  = sdkerrors.Register(types.ModuleName, 88, "invalid balance key format")
	ErrEmptyCollectionIDInBalanceKey            = sdkerrors.Register(types.ModuleName, 89, "empty collection ID in balance key")
	ErrCollectionIDCannotBeZero                 = sdkerrors.Register(types.ModuleName, 90, "collection ID cannot be zero")
	ErrEmptyAddressInBalanceKey                 = sdkerrors.Register(types.ModuleName, 91, "empty address in balance key")
	ErrBalanceKeyDelimiterConflict              = sdkerrors.Register(types.ModuleName, 92, "balance key components cannot contain delimiter")
	ErrApprovalNotFound                         = sdkerrors.Register(types.ModuleName, 93, "approval not found")
	ErrPathStringEmpty                          = sdkerrors.Register(types.ModuleName, 94, "path string cannot be empty")
	ErrPathStringExceedsMaxLength               = sdkerrors.Register(types.ModuleName, 95, "path string exceeds maximum length")
	ErrGeneratedPathAddressEmpty                = sdkerrors.Register(types.ModuleName, 96, "generated path address is empty")
	ErrGeneratedPathAddressConversionFailed     = sdkerrors.Register(types.ModuleName, 97, "generated path address cannot be converted to string")
	ErrMintAddressInAddressList                 = sdkerrors.Register(types.ModuleName, 98, "Mint address cannot be included in address list with other addresses")
	ErrCosmosCoinBackedPathConversionNil        = sdkerrors.Register(types.ModuleName, 99, "cosmos coin backed path conversion or sideA is nil")
	ErrDenomNotAllowed                          = sdkerrors.Register(types.ModuleName, 100, "denom is not allowed")
	ErrPathAddressNotReserved                   = sdkerrors.Register(types.ModuleName, 101, "generated path address was not properly reserved")
	ErrDuplicateIBCWrapperPathDenom             = sdkerrors.Register(types.ModuleName, 102, "duplicate ibc wrapper path denom")
	ErrDuplicateAliasPathDenom                  = sdkerrors.Register(types.ModuleName, 103, "duplicate alias path denom")
	ErrAliasPathDenomConflictsWithWrapper       = sdkerrors.Register(types.ModuleName, 104, "alias path denom conflicts with wrapper denom")
	ErrDuplicatePathSymbol                      = sdkerrors.Register(types.ModuleName, 105, "duplicate path symbol")
	ErrDuplicateDenomUnitSymbol                 = sdkerrors.Register(types.ModuleName, 106, "duplicate denom unit symbol")
	ErrDenomUnitDecimalsCannotBeZero            = sdkerrors.Register(types.ModuleName, 107, "denom unit decimals cannot be 0")
	ErrDuplicateDenomUnitDecimals               = sdkerrors.Register(types.ModuleName, 108, "duplicate denom unit decimals")
	ErrMultipleDefaultDisplayDenomUnits         = sdkerrors.Register(types.ModuleName, 109, "only one denom unit per path can have isDefaultDisplay set to true")
	ErrInvalidDenomFormat                       = sdkerrors.Register(types.ModuleName, 110, "invalid denom format")
	ErrAliasPathNotFound                        = sdkerrors.Register(types.ModuleName, 111, "alias path not found for denom")
)
