// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: badges/approval_conditions.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CoinTransfer struct {
	// The address of the recipient of the transfer.
	To string `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	// The sdk.Coins to be transferred.
	Coins []*types.Coin `protobuf:"bytes,2,rep,name=coins,proto3" json:"coins,omitempty"`
	// By default, the from address is the initiator of the transaction.
	// If this is set to true, we will override the from address with the approver address.
	// Note: This is not applicable for collection approvals (since approverAddress == '').
	OverrideFromWithApproverAddress bool `protobuf:"varint,3,opt,name=overrideFromWithApproverAddress,proto3" json:"overrideFromWithApproverAddress,omitempty"`
	// By default, the to address is what is specified in the coin transfer.
	// If this is set to true, we will override the to address with the initiator of the transaction.
	OverrideToWithInitiator bool `protobuf:"varint,4,opt,name=overrideToWithInitiator,proto3" json:"overrideToWithInitiator,omitempty"`
}

func (m *CoinTransfer) Reset()         { *m = CoinTransfer{} }
func (m *CoinTransfer) String() string { return proto.CompactTextString(m) }
func (*CoinTransfer) ProtoMessage()    {}
func (*CoinTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{0}
}
func (m *CoinTransfer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CoinTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CoinTransfer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CoinTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinTransfer.Merge(m, src)
}
func (m *CoinTransfer) XXX_Size() int {
	return m.Size()
}
func (m *CoinTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_CoinTransfer proto.InternalMessageInfo

func (m *CoinTransfer) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CoinTransfer) GetCoins() []*types.Coin {
	if m != nil {
		return m.Coins
	}
	return nil
}

func (m *CoinTransfer) GetOverrideFromWithApproverAddress() bool {
	if m != nil {
		return m.OverrideFromWithApproverAddress
	}
	return false
}

func (m *CoinTransfer) GetOverrideToWithInitiator() bool {
	if m != nil {
		return m.OverrideToWithInitiator
	}
	return false
}

// MustOwnTokens represents a condition where a user must own specific tokens
// to be approved to transfer.
//
// - collectionId: The ID of the collection for the tokens that must be owned
// - amountRange: The range of amounts the user must own (min to max)
// - ownershipTimes: The time ranges during which the user must own the tokens.
// - tokenIds: The token IDs the user must own.
// - overrideWithCurrentTime: If true, auto override ownershipTimes with the current time.
// - mustSatisfyForAllAssets: If true, the user must own all specified tokens; otherwise, owning any one for >= 1 millisecond is sufficient.
type MustOwnTokens struct {
	// The ID of the collection.
	CollectionId Uint `protobuf:"bytes,1,opt,name=collectionId,proto3,customtype=Uint" json:"collectionId"`
	// The range of amounts the user must own (min to max).
	AmountRange *UintRange `protobuf:"bytes,2,opt,name=amountRange,proto3" json:"amountRange,omitempty"`
	// The time ranges during which the user must own the tokens.
	OwnershipTimes []*UintRange `protobuf:"bytes,3,rep,name=ownershipTimes,proto3" json:"ownershipTimes,omitempty"`
	// The token IDs the user must own.
	TokenIds []*UintRange `protobuf:"bytes,4,rep,name=tokenIds,proto3" json:"tokenIds,omitempty"`
	// If true, override ownershipTimes with the current time.
	OverrideWithCurrentTime bool `protobuf:"varint,5,opt,name=overrideWithCurrentTime,proto3" json:"overrideWithCurrentTime,omitempty"`
	// If true, the user must meet ownership requirements for all specified tokens; else, must meet requirements for any single token.
	MustSatisfyForAllAssets bool `protobuf:"varint,6,opt,name=mustSatisfyForAllAssets,proto3" json:"mustSatisfyForAllAssets,omitempty"`
	// The party to check ownership for. Options are "initiator", "sender", "recipient", or any valid bb1 address.
	// If a valid bb1 address is provided, ownership will be checked for that specific address.
	// This enables use cases like halt tokens where ownership is checked for an arbitrary address (e.g., halt token owner).
	// Defaults to "initiator" if empty or if the value is not a recognized option or valid bb1 address.
	OwnershipCheckParty string `protobuf:"bytes,7,opt,name=ownershipCheckParty,proto3" json:"ownershipCheckParty,omitempty"`
}

func (m *MustOwnTokens) Reset()         { *m = MustOwnTokens{} }
func (m *MustOwnTokens) String() string { return proto.CompactTextString(m) }
func (*MustOwnTokens) ProtoMessage()    {}
func (*MustOwnTokens) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{1}
}
func (m *MustOwnTokens) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MustOwnTokens) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MustOwnTokens.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MustOwnTokens) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MustOwnTokens.Merge(m, src)
}
func (m *MustOwnTokens) XXX_Size() int {
	return m.Size()
}
func (m *MustOwnTokens) XXX_DiscardUnknown() {
	xxx_messageInfo_MustOwnTokens.DiscardUnknown(m)
}

var xxx_messageInfo_MustOwnTokens proto.InternalMessageInfo

func (m *MustOwnTokens) GetAmountRange() *UintRange {
	if m != nil {
		return m.AmountRange
	}
	return nil
}

func (m *MustOwnTokens) GetOwnershipTimes() []*UintRange {
	if m != nil {
		return m.OwnershipTimes
	}
	return nil
}

func (m *MustOwnTokens) GetTokenIds() []*UintRange {
	if m != nil {
		return m.TokenIds
	}
	return nil
}

func (m *MustOwnTokens) GetOverrideWithCurrentTime() bool {
	if m != nil {
		return m.OverrideWithCurrentTime
	}
	return false
}

func (m *MustOwnTokens) GetMustSatisfyForAllAssets() bool {
	if m != nil {
		return m.MustSatisfyForAllAssets
	}
	return false
}

func (m *MustOwnTokens) GetOwnershipCheckParty() string {
	if m != nil {
		return m.OwnershipCheckParty
	}
	return ""
}

// DynamicStoreChallenge defines a challenge that requires the initiator to pass a dynamic store check.
type DynamicStoreChallenge struct {
	// The ID of the dynamic store to check.
	StoreId Uint `protobuf:"bytes,1,opt,name=storeId,proto3,customtype=Uint" json:"storeId"`
	// The party to check ownership for. Options are "initiator", "sender", "recipient", or any valid bb1 address.
	// If a valid bb1 address is provided, ownership will be checked for that specific address.
	// This enables use cases like halt tokens where ownership is checked for an arbitrary address (e.g., halt token owner).
	// Defaults to "initiator" if empty or if the value is not a recognized option or valid bb1 address.
	OwnershipCheckParty string `protobuf:"bytes,2,opt,name=ownershipCheckParty,proto3" json:"ownershipCheckParty,omitempty"`
}

func (m *DynamicStoreChallenge) Reset()         { *m = DynamicStoreChallenge{} }
func (m *DynamicStoreChallenge) String() string { return proto.CompactTextString(m) }
func (*DynamicStoreChallenge) ProtoMessage()    {}
func (*DynamicStoreChallenge) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{2}
}
func (m *DynamicStoreChallenge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DynamicStoreChallenge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DynamicStoreChallenge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DynamicStoreChallenge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamicStoreChallenge.Merge(m, src)
}
func (m *DynamicStoreChallenge) XXX_Size() int {
	return m.Size()
}
func (m *DynamicStoreChallenge) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamicStoreChallenge.DiscardUnknown(m)
}

var xxx_messageInfo_DynamicStoreChallenge proto.InternalMessageInfo

func (m *DynamicStoreChallenge) GetOwnershipCheckParty() string {
	if m != nil {
		return m.OwnershipCheckParty
	}
	return ""
}

// AddressChecks defines checks for address types (WASM contract, liquidity pool, etc.)
type AddressChecks struct {
	// Require the address to be a WASM contract.
	MustBeWasmContract bool `protobuf:"varint,1,opt,name=mustBeWasmContract,proto3" json:"mustBeWasmContract,omitempty"`
	// Require the address to not be a WASM contract.
	MustNotBeWasmContract bool `protobuf:"varint,2,opt,name=mustNotBeWasmContract,proto3" json:"mustNotBeWasmContract,omitempty"`
	// Require the address to be a liquidity pool.
	MustBeLiquidityPool bool `protobuf:"varint,3,opt,name=mustBeLiquidityPool,proto3" json:"mustBeLiquidityPool,omitempty"`
	// Require the address to not be a liquidity pool.
	MustNotBeLiquidityPool bool `protobuf:"varint,4,opt,name=mustNotBeLiquidityPool,proto3" json:"mustNotBeLiquidityPool,omitempty"`
}

func (m *AddressChecks) Reset()         { *m = AddressChecks{} }
func (m *AddressChecks) String() string { return proto.CompactTextString(m) }
func (*AddressChecks) ProtoMessage()    {}
func (*AddressChecks) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{3}
}
func (m *AddressChecks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddressChecks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddressChecks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddressChecks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddressChecks.Merge(m, src)
}
func (m *AddressChecks) XXX_Size() int {
	return m.Size()
}
func (m *AddressChecks) XXX_DiscardUnknown() {
	xxx_messageInfo_AddressChecks.DiscardUnknown(m)
}

var xxx_messageInfo_AddressChecks proto.InternalMessageInfo

func (m *AddressChecks) GetMustBeWasmContract() bool {
	if m != nil {
		return m.MustBeWasmContract
	}
	return false
}

func (m *AddressChecks) GetMustNotBeWasmContract() bool {
	if m != nil {
		return m.MustNotBeWasmContract
	}
	return false
}

func (m *AddressChecks) GetMustBeLiquidityPool() bool {
	if m != nil {
		return m.MustBeLiquidityPool
	}
	return false
}

func (m *AddressChecks) GetMustNotBeLiquidityPool() bool {
	if m != nil {
		return m.MustNotBeLiquidityPool
	}
	return false
}

// AltTimeChecks defines alternative time-based checks for approval denial.
// If the transfer time falls within any of the specified offline hours or days, the approval is denied.
// Uses UTC timezone for neutral timezone approach.
// offlineHours: ranges of hours (0-23) when transfers should be denied
// offlineDays: ranges of days (0-6, where 0=Sunday, 1=Monday, ..., 6=Saturday) when transfers should be denied
type AltTimeChecks struct {
	// Hours (0-23) when transfers should be denied. Uses UTC timezone.
	OfflineHours []*UintRange `protobuf:"bytes,1,rep,name=offlineHours,proto3" json:"offlineHours,omitempty"`
	// Days (0-6, where 0=Sunday, 1=Monday, ..., 6=Saturday) when transfers should be denied. Uses UTC timezone.
	OfflineDays []*UintRange `protobuf:"bytes,2,rep,name=offlineDays,proto3" json:"offlineDays,omitempty"`
}

func (m *AltTimeChecks) Reset()         { *m = AltTimeChecks{} }
func (m *AltTimeChecks) String() string { return proto.CompactTextString(m) }
func (*AltTimeChecks) ProtoMessage()    {}
func (*AltTimeChecks) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{4}
}
func (m *AltTimeChecks) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AltTimeChecks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AltTimeChecks.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AltTimeChecks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AltTimeChecks.Merge(m, src)
}
func (m *AltTimeChecks) XXX_Size() int {
	return m.Size()
}
func (m *AltTimeChecks) XXX_DiscardUnknown() {
	xxx_messageInfo_AltTimeChecks.DiscardUnknown(m)
}

var xxx_messageInfo_AltTimeChecks proto.InternalMessageInfo

func (m *AltTimeChecks) GetOfflineHours() []*UintRange {
	if m != nil {
		return m.OfflineHours
	}
	return nil
}

func (m *AltTimeChecks) GetOfflineDays() []*UintRange {
	if m != nil {
		return m.OfflineDays
	}
	return nil
}

// UserRoyalties defines the royalties for a user.
type UserRoyalties struct {
	// Percentage of the transfer amount to apply as royalties. 1 to 10000 represents basis points.
	Percentage Uint `protobuf:"bytes,1,opt,name=percentage,proto3,customtype=Uint" json:"percentage"`
	// Payout address for the royalties.
	PayoutAddress string `protobuf:"bytes,2,opt,name=payoutAddress,proto3" json:"payoutAddress,omitempty"`
}

func (m *UserRoyalties) Reset()         { *m = UserRoyalties{} }
func (m *UserRoyalties) String() string { return proto.CompactTextString(m) }
func (*UserRoyalties) ProtoMessage()    {}
func (*UserRoyalties) Descriptor() ([]byte, []int) {
	return fileDescriptor_f5c292244a512887, []int{5}
}
func (m *UserRoyalties) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UserRoyalties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UserRoyalties.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UserRoyalties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRoyalties.Merge(m, src)
}
func (m *UserRoyalties) XXX_Size() int {
	return m.Size()
}
func (m *UserRoyalties) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRoyalties.DiscardUnknown(m)
}

var xxx_messageInfo_UserRoyalties proto.InternalMessageInfo

func (m *UserRoyalties) GetPayoutAddress() string {
	if m != nil {
		return m.PayoutAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*CoinTransfer)(nil), "badges.CoinTransfer")
	proto.RegisterType((*MustOwnTokens)(nil), "badges.MustOwnTokens")
	proto.RegisterType((*DynamicStoreChallenge)(nil), "badges.DynamicStoreChallenge")
	proto.RegisterType((*AddressChecks)(nil), "badges.AddressChecks")
	proto.RegisterType((*AltTimeChecks)(nil), "badges.AltTimeChecks")
	proto.RegisterType((*UserRoyalties)(nil), "badges.UserRoyalties")
}

func init() { proto.RegisterFile("badges/approval_conditions.proto", fileDescriptor_f5c292244a512887) }

var fileDescriptor_f5c292244a512887 = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xcd, 0x6f, 0xd3, 0x30,
	0x14, 0x6f, 0xda, 0x7d, 0xe1, 0xb5, 0x93, 0x30, 0x0c, 0xc2, 0x0e, 0x59, 0x55, 0x21, 0xd4, 0x03,
	0x24, 0xfb, 0x00, 0x04, 0xc7, 0xae, 0xd3, 0xb4, 0x49, 0x03, 0xa6, 0xac, 0xd3, 0x24, 0x2e, 0xc8,
	0x4d, 0xdc, 0xd6, 0x5a, 0xe2, 0x97, 0xd9, 0xce, 0x46, 0xc4, 0x9d, 0x33, 0x7f, 0xd6, 0x8e, 0x93,
	0xb8, 0x20, 0x0e, 0x03, 0x6d, 0xff, 0x08, 0x72, 0x92, 0x4e, 0x6d, 0x95, 0x88, 0x5b, 0xfa, 0x7e,
	0x1f, 0xf6, 0x7b, 0xef, 0x57, 0xa3, 0x66, 0x9f, 0xf8, 0x43, 0x2a, 0x1d, 0x12, 0x45, 0x02, 0x2e,
	0x48, 0xf0, 0xc5, 0x03, 0xee, 0x33, 0xc5, 0x80, 0x4b, 0x3b, 0x12, 0xa0, 0x00, 0x2f, 0x64, 0x8c,
	0xb5, 0xc7, 0x43, 0x18, 0x42, 0x5a, 0x72, 0xf4, 0x57, 0x86, 0xae, 0xad, 0xe6, 0xfa, 0x3e, 0x09,
	0x08, 0xf7, 0x68, 0x2e, 0x5a, 0xb3, 0x3c, 0x90, 0x21, 0xe8, 0xb2, 0xa4, 0xce, 0xc5, 0x66, 0x9f,
	0x2a, 0xb2, 0xe9, 0x78, 0xc0, 0x78, 0x86, 0xb7, 0x7e, 0x1a, 0xa8, 0xde, 0x05, 0xc6, 0x7b, 0x82,
	0x70, 0x39, 0xa0, 0x02, 0xaf, 0xa0, 0xaa, 0x02, 0xd3, 0x68, 0x1a, 0xed, 0x07, 0x6e, 0x55, 0x01,
	0x76, 0xd0, 0xbc, 0xa6, 0x4b, 0xb3, 0xda, 0xac, 0xb5, 0x97, 0xb7, 0x9e, 0xd9, 0x99, 0xa1, 0xad,
	0x0d, 0xed, 0xdc, 0xd0, 0xd6, 0x0e, 0x6e, 0xc6, 0xc3, 0xfb, 0x68, 0x1d, 0x2e, 0xa8, 0x10, 0xcc,
	0xa7, 0x7b, 0x02, 0xc2, 0x53, 0xa6, 0x46, 0x9d, 0xb4, 0x27, 0x2a, 0x3a, 0xbe, 0x2f, 0xa8, 0x94,
	0x66, 0xad, 0x69, 0xb4, 0x97, 0xdc, 0xff, 0xd1, 0xf0, 0x3b, 0xf4, 0x74, 0x4c, 0xe9, 0x81, 0x26,
	0x1c, 0x70, 0xa6, 0x18, 0x51, 0x20, 0xcc, 0xb9, 0xd4, 0xa1, 0x0c, 0x6e, 0x7d, 0xaf, 0xa1, 0xc6,
	0x87, 0x58, 0xaa, 0x4f, 0x97, 0xbc, 0x07, 0x67, 0x94, 0x4b, 0xbc, 0x81, 0xea, 0x1e, 0x04, 0x01,
	0xf5, 0xf4, 0x44, 0x0f, 0xfc, 0xac, 0xc1, 0x9d, 0xfa, 0xd5, 0xcd, 0x7a, 0xe5, 0xf7, 0xcd, 0xfa,
	0xdc, 0x09, 0xe3, 0xca, 0x9d, 0x62, 0xe0, 0x6d, 0xb4, 0x4c, 0x42, 0x88, 0xb9, 0x72, 0x09, 0x1f,
	0x52, 0xb3, 0xda, 0x34, 0xda, 0xcb, 0x5b, 0x0f, 0xed, 0x6c, 0xcc, 0x76, 0x2a, 0xd0, 0x80, 0x3b,
	0xc9, 0xc2, 0xef, 0xd1, 0x0a, 0x5c, 0x72, 0x2a, 0xe4, 0x88, 0x45, 0x3d, 0x16, 0x52, 0xdd, 0x6b,
	0xad, 0x58, 0x37, 0x43, 0xc4, 0xaf, 0xd0, 0x92, 0xd2, 0x77, 0x3d, 0xf0, 0xa5, 0x39, 0x57, 0x26,
	0xba, 0xa7, 0x4c, 0x0e, 0x47, 0xf7, 0xde, 0x8d, 0x85, 0xa0, 0x5c, 0x69, 0x2b, 0x73, 0x7e, 0x7a,
	0x38, 0x33, 0xb0, 0x56, 0x86, 0xb1, 0x54, 0xc7, 0x44, 0x31, 0x39, 0x48, 0xf6, 0x40, 0x74, 0x82,
	0xa0, 0x23, 0x25, 0x55, 0xd2, 0x5c, 0xc8, 0x94, 0x25, 0x30, 0xde, 0x40, 0x8f, 0xee, 0x2f, 0xdd,
	0x1d, 0x51, 0xef, 0xec, 0x88, 0x08, 0x95, 0x98, 0x8b, 0x69, 0x58, 0x8a, 0xa0, 0xd6, 0x39, 0x5a,
	0xdd, 0x4d, 0x38, 0x09, 0x99, 0x77, 0xac, 0x40, 0xd0, 0xee, 0x88, 0x04, 0x01, 0xd5, 0x83, 0x7a,
	0x81, 0x16, 0xa5, 0xae, 0x94, 0xac, 0x62, 0x0c, 0x96, 0x1d, 0x59, 0x2d, 0x3f, 0xf2, 0x8f, 0x81,
	0x1a, 0x79, 0x82, 0xd2, 0xaa, 0xc4, 0x36, 0xc2, 0xba, 0xa3, 0x1d, 0x7a, 0x4a, 0x64, 0xd8, 0x05,
	0xae, 0x04, 0xf1, 0x54, 0x7a, 0xec, 0x92, 0x5b, 0x80, 0xe0, 0xd7, 0x68, 0x55, 0x57, 0x3f, 0xc2,
	0xac, 0xa4, 0x9a, 0x4a, 0x8a, 0x41, 0x7d, 0xd3, 0xcc, 0xeb, 0x90, 0x9d, 0xc7, 0xcc, 0x67, 0x2a,
	0x39, 0x02, 0x08, 0xf2, 0xac, 0x17, 0x41, 0xf8, 0x2d, 0x7a, 0x72, 0x6f, 0x35, 0x2d, 0xca, 0xe2,
	0x5d, 0x82, 0xb6, 0xbe, 0xa1, 0x46, 0x27, 0x48, 0x77, 0x99, 0x37, 0xf8, 0x06, 0xd5, 0x61, 0x30,
	0x08, 0x18, 0xa7, 0xfb, 0x10, 0x0b, 0x69, 0x1a, 0x65, 0xf1, 0x99, 0xa2, 0xe9, 0x84, 0xe7, 0xbf,
	0x77, 0x49, 0x32, 0xfe, 0x83, 0x17, 0x25, 0x7c, 0x82, 0xd5, 0xf2, 0x50, 0xe3, 0x44, 0x52, 0xe1,
	0x42, 0x42, 0x02, 0xc5, 0xa8, 0xc4, 0x2f, 0x11, 0x8a, 0xa8, 0xf0, 0x28, 0x57, 0x64, 0x48, 0x0b,
	0x97, 0x39, 0x81, 0xe3, 0xe7, 0xa8, 0x11, 0x91, 0x04, 0x62, 0x35, 0x7e, 0x0b, 0xb2, 0x4d, 0x4e,
	0x17, 0x77, 0x0e, 0xaf, 0x6e, 0x2d, 0xe3, 0xfa, 0xd6, 0x32, 0xfe, 0xde, 0x5a, 0xc6, 0x8f, 0x3b,
	0xab, 0x72, 0x7d, 0x67, 0x55, 0x7e, 0xdd, 0x59, 0x95, 0xcf, 0x5b, 0x43, 0xa6, 0x46, 0x71, 0xdf,
	0xf6, 0x20, 0x74, 0xfa, 0x4c, 0x8d, 0x1f, 0xbd, 0xf1, 0x97, 0x37, 0x22, 0x8c, 0x3b, 0x5f, 0x9d,
	0xbc, 0xae, 0x92, 0x88, 0xca, 0xfe, 0x42, 0xfa, 0xd4, 0x6d, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x0a, 0xfc, 0x26, 0x0a, 0x63, 0x05, 0x00, 0x00,
}

func (m *CoinTransfer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CoinTransfer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CoinTransfer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OverrideToWithInitiator {
		i--
		if m.OverrideToWithInitiator {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.OverrideFromWithApproverAddress {
		i--
		if m.OverrideFromWithApproverAddress {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintApprovalConditions(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MustOwnTokens) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MustOwnTokens) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MustOwnTokens) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnershipCheckParty) > 0 {
		i -= len(m.OwnershipCheckParty)
		copy(dAtA[i:], m.OwnershipCheckParty)
		i = encodeVarintApprovalConditions(dAtA, i, uint64(len(m.OwnershipCheckParty)))
		i--
		dAtA[i] = 0x3a
	}
	if m.MustSatisfyForAllAssets {
		i--
		if m.MustSatisfyForAllAssets {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.OverrideWithCurrentTime {
		i--
		if m.OverrideWithCurrentTime {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.TokenIds) > 0 {
		for iNdEx := len(m.TokenIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.OwnershipTimes) > 0 {
		for iNdEx := len(m.OwnershipTimes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OwnershipTimes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.AmountRange != nil {
		{
			size, err := m.AmountRange.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.CollectionId.Size()
		i -= size
		if _, err := m.CollectionId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *DynamicStoreChallenge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DynamicStoreChallenge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DynamicStoreChallenge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OwnershipCheckParty) > 0 {
		i -= len(m.OwnershipCheckParty)
		copy(dAtA[i:], m.OwnershipCheckParty)
		i = encodeVarintApprovalConditions(dAtA, i, uint64(len(m.OwnershipCheckParty)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.StoreId.Size()
		i -= size
		if _, err := m.StoreId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AddressChecks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddressChecks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddressChecks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MustNotBeLiquidityPool {
		i--
		if m.MustNotBeLiquidityPool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.MustBeLiquidityPool {
		i--
		if m.MustBeLiquidityPool {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.MustNotBeWasmContract {
		i--
		if m.MustNotBeWasmContract {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MustBeWasmContract {
		i--
		if m.MustBeWasmContract {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AltTimeChecks) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AltTimeChecks) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AltTimeChecks) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OfflineDays) > 0 {
		for iNdEx := len(m.OfflineDays) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfflineDays[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.OfflineHours) > 0 {
		for iNdEx := len(m.OfflineHours) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OfflineHours[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *UserRoyalties) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UserRoyalties) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *UserRoyalties) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PayoutAddress) > 0 {
		i -= len(m.PayoutAddress)
		copy(dAtA[i:], m.PayoutAddress)
		i = encodeVarintApprovalConditions(dAtA, i, uint64(len(m.PayoutAddress)))
		i--
		dAtA[i] = 0x12
	}
	{
		size := m.Percentage.Size()
		i -= size
		if _, err := m.Percentage.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintApprovalConditions(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintApprovalConditions(dAtA []byte, offset int, v uint64) int {
	offset -= sovApprovalConditions(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CoinTransfer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovApprovalConditions(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovApprovalConditions(uint64(l))
		}
	}
	if m.OverrideFromWithApproverAddress {
		n += 2
	}
	if m.OverrideToWithInitiator {
		n += 2
	}
	return n
}

func (m *MustOwnTokens) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.CollectionId.Size()
	n += 1 + l + sovApprovalConditions(uint64(l))
	if m.AmountRange != nil {
		l = m.AmountRange.Size()
		n += 1 + l + sovApprovalConditions(uint64(l))
	}
	if len(m.OwnershipTimes) > 0 {
		for _, e := range m.OwnershipTimes {
			l = e.Size()
			n += 1 + l + sovApprovalConditions(uint64(l))
		}
	}
	if len(m.TokenIds) > 0 {
		for _, e := range m.TokenIds {
			l = e.Size()
			n += 1 + l + sovApprovalConditions(uint64(l))
		}
	}
	if m.OverrideWithCurrentTime {
		n += 2
	}
	if m.MustSatisfyForAllAssets {
		n += 2
	}
	l = len(m.OwnershipCheckParty)
	if l > 0 {
		n += 1 + l + sovApprovalConditions(uint64(l))
	}
	return n
}

func (m *DynamicStoreChallenge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.StoreId.Size()
	n += 1 + l + sovApprovalConditions(uint64(l))
	l = len(m.OwnershipCheckParty)
	if l > 0 {
		n += 1 + l + sovApprovalConditions(uint64(l))
	}
	return n
}

func (m *AddressChecks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MustBeWasmContract {
		n += 2
	}
	if m.MustNotBeWasmContract {
		n += 2
	}
	if m.MustBeLiquidityPool {
		n += 2
	}
	if m.MustNotBeLiquidityPool {
		n += 2
	}
	return n
}

func (m *AltTimeChecks) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OfflineHours) > 0 {
		for _, e := range m.OfflineHours {
			l = e.Size()
			n += 1 + l + sovApprovalConditions(uint64(l))
		}
	}
	if len(m.OfflineDays) > 0 {
		for _, e := range m.OfflineDays {
			l = e.Size()
			n += 1 + l + sovApprovalConditions(uint64(l))
		}
	}
	return n
}

func (m *UserRoyalties) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Percentage.Size()
	n += 1 + l + sovApprovalConditions(uint64(l))
	l = len(m.PayoutAddress)
	if l > 0 {
		n += 1 + l + sovApprovalConditions(uint64(l))
	}
	return n
}

func sovApprovalConditions(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApprovalConditions(x uint64) (n int) {
	return sovApprovalConditions(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CoinTransfer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CoinTransfer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CoinTransfer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, &types.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverrideFromWithApproverAddress", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverrideFromWithApproverAddress = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverrideToWithInitiator", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverrideToWithInitiator = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MustOwnTokens) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MustOwnTokens: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MustOwnTokens: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CollectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CollectionId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountRange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AmountRange == nil {
				m.AmountRange = &UintRange{}
			}
			if err := m.AmountRange.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnershipTimes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnershipTimes = append(m.OwnershipTimes, &UintRange{})
			if err := m.OwnershipTimes[len(m.OwnershipTimes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenIds = append(m.TokenIds, &UintRange{})
			if err := m.TokenIds[len(m.TokenIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverrideWithCurrentTime", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverrideWithCurrentTime = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MustSatisfyForAllAssets", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MustSatisfyForAllAssets = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnershipCheckParty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnershipCheckParty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DynamicStoreChallenge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DynamicStoreChallenge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DynamicStoreChallenge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StoreId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StoreId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnershipCheckParty", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnershipCheckParty = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AddressChecks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddressChecks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddressChecks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MustBeWasmContract", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MustBeWasmContract = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MustNotBeWasmContract", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MustNotBeWasmContract = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MustBeLiquidityPool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MustBeLiquidityPool = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MustNotBeLiquidityPool", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MustNotBeLiquidityPool = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AltTimeChecks) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AltTimeChecks: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AltTimeChecks: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfflineHours", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfflineHours = append(m.OfflineHours, &UintRange{})
			if err := m.OfflineHours[len(m.OfflineHours)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OfflineDays", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OfflineDays = append(m.OfflineDays, &UintRange{})
			if err := m.OfflineDays[len(m.OfflineDays)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UserRoyalties) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UserRoyalties: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UserRoyalties: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Percentage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Percentage.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayoutAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayoutAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApprovalConditions(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthApprovalConditions
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApprovalConditions(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApprovalConditions
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApprovalConditions
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApprovalConditions
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApprovalConditions
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApprovalConditions
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApprovalConditions        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApprovalConditions          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApprovalConditions = fmt.Errorf("proto: unexpected end of group")
)
