// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: badges/badges.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/codec/types"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// BitBadge defines a badge type. Think of this like the smart contract definition
type BitBadge struct {
	// id defines the unique identifier of the Badge classification, similar to the contract address of ERC721
	// starts at 0 and increments by 1 each badge
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// uri for the class metadata stored off chain. must match a valid metadata standard (bitbadge, collection, etc)
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// this is permanent and never changable; use this for asserting the permanence of the metadata
	MetadataHash string `protobuf:"bytes,3,opt,name=metadata_hash,json=metadataHash,proto3" json:"metadata_hash,omitempty"`
	// manager address of the class; can have special permissions; is used as the reserve address for the assets
	Manager uint64 `protobuf:"varint,4,opt,name=manager,proto3" json:"manager,omitempty"`
	//
	//Flag bits are in the following order from left to right; leading zeroes are applied and any future additions will be appended to the right
	//
	//can_manager_transfer: can the manager transfer managerial privileges to another address
	//can_update_uris: can the manager update the uris of the class and subassets; if false, locked forever
	//forceful_transfers: if true, one can send a badge to an account without pending approval; these badges should not by default be displayed on public profiles (can also use collections)
	//can_create: when true, manager can create more subassets of the class; once set to false, it is locked
	//can_revoke: when true, manager can revoke subassets of the class (including null address); once set to false, it is locked
	//can_freeze: when true, manager can freeze addresseses from transferring; once set to false, it is locked
	//frozen_by_default: when true, all addresses are considered frozen and must be unfrozen to transfer; when false, all addresses are considered unfrozen and must be frozen to freeze
	//manager is not frozen by default
	//
	//More permissions to be added
	PermissionFlags uint64 `protobuf:"varint,5,opt,name=permission_flags,json=permissionFlags,proto3" json:"permission_flags,omitempty"`
	// if frozen_by_default is true, this is an accumulator of unfrozen addresses; and vice versa for false
	//big.Int will always only be 32 uint64s long
	FreezeAddresses []uint64 `protobuf:"varint,10,rep,packed,name=freeze_addresses,json=freezeAddresses,proto3" json:"freeze_addresses,omitempty"`
	// uri for the subassets metadata stored off chain; include {id} in the string, it will be replaced with the subasset id
	// if not specified, uses a default Class (ID # 1) like metadata
	SubassetUriFormat string `protobuf:"bytes,11,opt,name=subasset_uri_format,json=subassetUriFormat,proto3" json:"subasset_uri_format,omitempty"`
	// starts at 0; each subasset created will incrementally have an increasing ID #
	NextSubassetId uint64 `protobuf:"varint,12,opt,name=next_subasset_id,json=nextSubassetId,proto3" json:"next_subasset_id,omitempty"`
	//only store if not 1 (default); will be sorted in order of subsasset ids; (maybe add defaut option in future)
	SubassetsTotalSupply []*Subasset `protobuf:"bytes,13,rep,name=subassets_total_supply,json=subassetsTotalSupply,proto3" json:"subassets_total_supply,omitempty"`
}

func (m *BitBadge) Reset()         { *m = BitBadge{} }
func (m *BitBadge) String() string { return proto.CompactTextString(m) }
func (*BitBadge) ProtoMessage()    {}
func (*BitBadge) Descriptor() ([]byte, []int) {
	return fileDescriptor_71eab594b779f631, []int{0}
}
func (m *BitBadge) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BitBadge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BitBadge.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BitBadge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BitBadge.Merge(m, src)
}
func (m *BitBadge) XXX_Size() int {
	return m.Size()
}
func (m *BitBadge) XXX_DiscardUnknown() {
	xxx_messageInfo_BitBadge.DiscardUnknown(m)
}

var xxx_messageInfo_BitBadge proto.InternalMessageInfo

func (m *BitBadge) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BitBadge) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *BitBadge) GetMetadataHash() string {
	if m != nil {
		return m.MetadataHash
	}
	return ""
}

func (m *BitBadge) GetManager() uint64 {
	if m != nil {
		return m.Manager
	}
	return 0
}

func (m *BitBadge) GetPermissionFlags() uint64 {
	if m != nil {
		return m.PermissionFlags
	}
	return 0
}

func (m *BitBadge) GetFreezeAddresses() []uint64 {
	if m != nil {
		return m.FreezeAddresses
	}
	return nil
}

func (m *BitBadge) GetSubassetUriFormat() string {
	if m != nil {
		return m.SubassetUriFormat
	}
	return ""
}

func (m *BitBadge) GetNextSubassetId() uint64 {
	if m != nil {
		return m.NextSubassetId
	}
	return 0
}

func (m *BitBadge) GetSubassetsTotalSupply() []*Subasset {
	if m != nil {
		return m.SubassetsTotalSupply
	}
	return nil
}

//Only will be created if supply >= 0
type Subasset struct {
	StartId uint64 `protobuf:"varint,1,opt,name=startId,proto3" json:"startId,omitempty"`
	EndId   uint64 `protobuf:"varint,2,opt,name=endId,proto3" json:"endId,omitempty"`
	Supply  uint64 `protobuf:"varint,3,opt,name=supply,proto3" json:"supply,omitempty"`
}

func (m *Subasset) Reset()         { *m = Subasset{} }
func (m *Subasset) String() string { return proto.CompactTextString(m) }
func (*Subasset) ProtoMessage()    {}
func (*Subasset) Descriptor() ([]byte, []int) {
	return fileDescriptor_71eab594b779f631, []int{1}
}
func (m *Subasset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Subasset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Subasset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Subasset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Subasset.Merge(m, src)
}
func (m *Subasset) XXX_Size() int {
	return m.Size()
}
func (m *Subasset) XXX_DiscardUnknown() {
	xxx_messageInfo_Subasset.DiscardUnknown(m)
}

var xxx_messageInfo_Subasset proto.InternalMessageInfo

func (m *Subasset) GetStartId() uint64 {
	if m != nil {
		return m.StartId
	}
	return 0
}

func (m *Subasset) GetEndId() uint64 {
	if m != nil {
		return m.EndId
	}
	return 0
}

func (m *Subasset) GetSupply() uint64 {
	if m != nil {
		return m.Supply
	}
	return 0
}

func init() {
	proto.RegisterType((*BitBadge)(nil), "trevormil.bitbadgeschain.badges.BitBadge")
	proto.RegisterType((*Subasset)(nil), "trevormil.bitbadgeschain.badges.Subasset")
}

func init() { proto.RegisterFile("badges/badges.proto", fileDescriptor_71eab594b779f631) }

var fileDescriptor_71eab594b779f631 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x9b, 0xa6, 0x1b, 0xc3, 0xfb, 0x43, 0xf1, 0xa6, 0xc9, 0x70, 0x08, 0xd5, 0xb8, 0x74,
	0x97, 0x44, 0x1a, 0x9f, 0x80, 0x1e, 0x26, 0x2a, 0x71, 0xca, 0xe0, 0xc2, 0xc5, 0x7a, 0x33, 0xbb,
	0x89, 0xa5, 0x24, 0x8e, 0xfc, 0x3a, 0x68, 0xe5, 0x53, 0xf0, 0xb1, 0x38, 0xf6, 0xc8, 0x11, 0xb5,
	0x5f, 0x83, 0x03, 0xb2, 0x53, 0x17, 0x71, 0xe2, 0x64, 0xbf, 0xbf, 0xe7, 0xf1, 0xa3, 0x47, 0xb6,
	0xc9, 0x65, 0x01, 0xa2, 0x94, 0x98, 0x0d, 0x4b, 0xda, 0x19, 0x6d, 0x35, 0x7d, 0x63, 0x8d, 0xfc,
	0xaa, 0x4d, 0xa3, 0xea, 0xb4, 0x50, 0x76, 0x90, 0x1e, 0x2b, 0x50, 0x6d, 0x3a, 0xec, 0x5f, 0xbf,
	0x2a, 0xb5, 0x2e, 0x6b, 0x99, 0x79, 0x7b, 0xd1, 0xaf, 0x32, 0x68, 0xd7, 0xc3, 0xd9, 0x9b, 0xdf,
	0x63, 0x72, 0xb2, 0x50, 0x76, 0xe1, 0x8c, 0xf4, 0x82, 0x8c, 0x95, 0x60, 0xd1, 0x2c, 0x9a, 0x4f,
	0xf2, 0xb1, 0x12, 0x74, 0x4a, 0xe2, 0xde, 0x28, 0x36, 0x9e, 0x45, 0xf3, 0xe7, 0xb9, 0xdb, 0xd2,
	0xb7, 0xe4, 0xbc, 0x91, 0x16, 0x04, 0x58, 0xe0, 0x15, 0x60, 0xc5, 0x62, 0xaf, 0x9d, 0x05, 0xf8,
	0x01, 0xb0, 0xa2, 0x8c, 0x3c, 0x6b, 0xa0, 0x85, 0x52, 0x1a, 0x36, 0xf1, 0x59, 0x61, 0xa4, 0xb7,
	0x64, 0xda, 0x49, 0xd3, 0x28, 0x44, 0xa5, 0x5b, 0xbe, 0xaa, 0xa1, 0x44, 0x76, 0xe4, 0x2d, 0x2f,
	0xfe, 0xf2, 0x7b, 0x87, 0x9d, 0x75, 0x65, 0xa4, 0xfc, 0x26, 0x39, 0x08, 0x61, 0x24, 0xa2, 0x44,
	0x46, 0x66, 0xb1, 0xb3, 0x0e, 0xfc, 0x7d, 0xc0, 0x34, 0x25, 0x97, 0xd8, 0x17, 0x80, 0x28, 0x2d,
	0xef, 0x8d, 0xe2, 0x2b, 0x6d, 0x1a, 0xb0, 0xec, 0xd4, 0x57, 0x7b, 0x19, 0xa4, 0xcf, 0x46, 0xdd,
	0x7b, 0x81, 0xce, 0xc9, 0xb4, 0x95, 0x4f, 0x96, 0x1f, 0x0e, 0x29, 0xc1, 0xce, 0x7c, 0x8b, 0x0b,
	0xc7, 0x1f, 0xf6, 0x78, 0x29, 0x28, 0x27, 0xd7, 0xc1, 0x84, 0xdc, 0x6a, 0x0b, 0x35, 0xc7, 0xbe,
	0xeb, 0xea, 0x35, 0x3b, 0x9f, 0xc5, 0xf3, 0xd3, 0xbb, 0xdb, 0xf4, 0x3f, 0x57, 0x9f, 0x86, 0xb0,
	0xfc, 0xea, 0x10, 0xf4, 0xc9, 0xe5, 0x3c, 0xf8, 0x98, 0x9b, 0x9c, 0x9c, 0x04, 0x87, 0xbb, 0x36,
	0xb4, 0x60, 0xec, 0x32, 0x3c, 0x41, 0x18, 0xe9, 0x15, 0x39, 0x92, 0xad, 0x58, 0x0a, 0xff, 0x12,
	0x93, 0x7c, 0x18, 0xe8, 0x35, 0x39, 0xde, 0x97, 0x89, 0x3d, 0xde, 0x4f, 0x8b, 0x8f, 0x3f, 0xb6,
	0x49, 0xb4, 0xd9, 0x26, 0xd1, 0xaf, 0x6d, 0x12, 0x7d, 0xdf, 0x25, 0xa3, 0xcd, 0x2e, 0x19, 0xfd,
	0xdc, 0x25, 0xa3, 0x2f, 0x77, 0xa5, 0xb2, 0x55, 0x5f, 0xa4, 0x8f, 0xba, 0xc9, 0x0e, 0xc5, 0xb3,
	0x7f, 0x8b, 0x67, 0x4f, 0xfb, 0xcf, 0x95, 0xd9, 0x75, 0x27, 0xb1, 0x38, 0xf6, 0xff, 0xe4, 0xdd,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc4, 0xde, 0xdf, 0x98, 0x7a, 0x02, 0x00, 0x00,
}

func (m *BitBadge) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BitBadge) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BitBadge) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SubassetsTotalSupply) > 0 {
		for iNdEx := len(m.SubassetsTotalSupply) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SubassetsTotalSupply[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintBadges(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x6a
		}
	}
	if m.NextSubassetId != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.NextSubassetId))
		i--
		dAtA[i] = 0x60
	}
	if len(m.SubassetUriFormat) > 0 {
		i -= len(m.SubassetUriFormat)
		copy(dAtA[i:], m.SubassetUriFormat)
		i = encodeVarintBadges(dAtA, i, uint64(len(m.SubassetUriFormat)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.FreezeAddresses) > 0 {
		dAtA2 := make([]byte, len(m.FreezeAddresses)*10)
		var j1 int
		for _, num := range m.FreezeAddresses {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintBadges(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x52
	}
	if m.PermissionFlags != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.PermissionFlags))
		i--
		dAtA[i] = 0x28
	}
	if m.Manager != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.Manager))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MetadataHash) > 0 {
		i -= len(m.MetadataHash)
		copy(dAtA[i:], m.MetadataHash)
		i = encodeVarintBadges(dAtA, i, uint64(len(m.MetadataHash)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Uri) > 0 {
		i -= len(m.Uri)
		copy(dAtA[i:], m.Uri)
		i = encodeVarintBadges(dAtA, i, uint64(len(m.Uri)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Subasset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Subasset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Subasset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Supply != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.Supply))
		i--
		dAtA[i] = 0x18
	}
	if m.EndId != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.EndId))
		i--
		dAtA[i] = 0x10
	}
	if m.StartId != 0 {
		i = encodeVarintBadges(dAtA, i, uint64(m.StartId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBadges(dAtA []byte, offset int, v uint64) int {
	offset -= sovBadges(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BitBadge) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovBadges(uint64(m.Id))
	}
	l = len(m.Uri)
	if l > 0 {
		n += 1 + l + sovBadges(uint64(l))
	}
	l = len(m.MetadataHash)
	if l > 0 {
		n += 1 + l + sovBadges(uint64(l))
	}
	if m.Manager != 0 {
		n += 1 + sovBadges(uint64(m.Manager))
	}
	if m.PermissionFlags != 0 {
		n += 1 + sovBadges(uint64(m.PermissionFlags))
	}
	if len(m.FreezeAddresses) > 0 {
		l = 0
		for _, e := range m.FreezeAddresses {
			l += sovBadges(uint64(e))
		}
		n += 1 + sovBadges(uint64(l)) + l
	}
	l = len(m.SubassetUriFormat)
	if l > 0 {
		n += 1 + l + sovBadges(uint64(l))
	}
	if m.NextSubassetId != 0 {
		n += 1 + sovBadges(uint64(m.NextSubassetId))
	}
	if len(m.SubassetsTotalSupply) > 0 {
		for _, e := range m.SubassetsTotalSupply {
			l = e.Size()
			n += 1 + l + sovBadges(uint64(l))
		}
	}
	return n
}

func (m *Subasset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StartId != 0 {
		n += 1 + sovBadges(uint64(m.StartId))
	}
	if m.EndId != 0 {
		n += 1 + sovBadges(uint64(m.EndId))
	}
	if m.Supply != 0 {
		n += 1 + sovBadges(uint64(m.Supply))
	}
	return n
}

func sovBadges(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBadges(x uint64) (n int) {
	return sovBadges(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BitBadge) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBadges
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BitBadge: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BitBadge: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBadges
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBadges
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MetadataHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBadges
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBadges
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MetadataHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Manager", wireType)
			}
			m.Manager = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Manager |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PermissionFlags", wireType)
			}
			m.PermissionFlags = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PermissionFlags |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBadges
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.FreezeAddresses = append(m.FreezeAddresses, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowBadges
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthBadges
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthBadges
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.FreezeAddresses) == 0 {
					m.FreezeAddresses = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowBadges
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.FreezeAddresses = append(m.FreezeAddresses, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field FreezeAddresses", wireType)
			}
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubassetUriFormat", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBadges
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBadges
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubassetUriFormat = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextSubassetId", wireType)
			}
			m.NextSubassetId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NextSubassetId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubassetsTotalSupply", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBadges
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBadges
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SubassetsTotalSupply = append(m.SubassetsTotalSupply, &Subasset{})
			if err := m.SubassetsTotalSupply[len(m.SubassetsTotalSupply)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipBadges(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBadges
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Subasset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBadges
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Subasset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Subasset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartId", wireType)
			}
			m.StartId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndId", wireType)
			}
			m.EndId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supply", wireType)
			}
			m.Supply = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Supply |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBadges(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBadges
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBadges(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBadges
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBadges
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBadges
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBadges
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBadges
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBadges        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBadges          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBadges = fmt.Errorf("proto: unexpected end of group")
)
