// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: badges/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the badges module's genesis state.
type GenesisState struct {
	Params           Params              `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	PortId           string              `protobuf:"bytes,2,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	Collections      []*BadgeCollection  `protobuf:"bytes,3,rep,name=collections,proto3" json:"collections,omitempty"`
	Balances         []*UserBalanceStore `protobuf:"bytes,4,rep,name=balances,proto3" json:"balances,omitempty"`
	BalanceStoreKeys []string            `protobuf:"bytes,5,rep,name=balanceStoreKeys,proto3" json:"balanceStoreKeys,omitempty"`
	Claims           []Uint              `protobuf:"bytes,6,rep,name=claims,proto3,customtype=Uint" json:"claims"`
	ClaimStoreKeys   []string            `protobuf:"bytes,7,rep,name=claimStoreKeys,proto3" json:"claimStoreKeys,omitempty"`
	NextCollectionId Uint                `protobuf:"bytes,8,opt,name=nextCollectionId,proto3,customtype=Uint" json:"nextCollectionId"`
	NextClaimId      Uint                `protobuf:"bytes,9,opt,name=nextClaimId,proto3,customtype=Uint" json:"nextClaimId"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_966136619b34853e, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetPortId() string {
	if m != nil {
		return m.PortId
	}
	return ""
}

func (m *GenesisState) GetCollections() []*BadgeCollection {
	if m != nil {
		return m.Collections
	}
	return nil
}

func (m *GenesisState) GetBalances() []*UserBalanceStore {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *GenesisState) GetBalanceStoreKeys() []string {
	if m != nil {
		return m.BalanceStoreKeys
	}
	return nil
}

func (m *GenesisState) GetClaimStoreKeys() []string {
	if m != nil {
		return m.ClaimStoreKeys
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "bitbadges.bitbadgeschain.badges.GenesisState")
}

func init() { proto.RegisterFile("badges/genesis.proto", fileDescriptor_966136619b34853e) }

var fileDescriptor_966136619b34853e = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x13, 0x53, 0xd3, 0x76, 0x52, 0xa4, 0x8c, 0x55, 0x87, 0x2e, 0xd2, 0x20, 0xa2, 0xc1,
	0x45, 0xa2, 0x75, 0xe3, 0x3a, 0x22, 0x52, 0x54, 0x90, 0x94, 0x6e, 0xdc, 0xc8, 0x24, 0x19, 0xd3,
	0x81, 0x34, 0x13, 0x32, 0x23, 0xb4, 0x6f, 0xe1, 0x63, 0x75, 0xd9, 0xa5, 0xb8, 0x28, 0x97, 0xf6,
	0x19, 0xee, 0xfe, 0x92, 0x64, 0x92, 0xe6, 0xb6, 0x17, 0xba, 0xca, 0xc9, 0x7f, 0xfe, 0xff, 0x9b,
	0x33, 0x87, 0x01, 0xa3, 0x00, 0x47, 0x31, 0xe1, 0x6e, 0x4c, 0x52, 0xc2, 0x29, 0x77, 0xb2, 0x9c,
	0x09, 0x06, 0x27, 0x01, 0x15, 0x55, 0xc3, 0x69, 0xaa, 0x70, 0x89, 0x69, 0xea, 0x54, 0xf5, 0x78,
	0x14, 0xb3, 0x98, 0x95, 0x5e, 0xb7, 0xa8, 0xaa, 0xd8, 0xf8, 0xa9, 0x84, 0x65, 0x38, 0xc7, 0x2b,
	0xc9, 0x1a, 0x23, 0x29, 0x86, 0x2c, 0x49, 0x48, 0x28, 0x28, 0x4b, 0xeb, 0xce, 0x33, 0xd9, 0x09,
	0x70, 0x82, 0xd3, 0x90, 0xd4, 0xf2, 0x73, 0x29, 0x8b, 0x1c, 0xa7, 0xfc, 0x37, 0xc9, 0xa5, 0xfe,
	0xf2, 0x56, 0x03, 0x83, 0x2f, 0xd5, 0x98, 0x73, 0x81, 0x05, 0x81, 0x9f, 0x81, 0x5e, 0x9d, 0x84,
	0x54, 0x4b, 0xb5, 0x8d, 0xe9, 0x1b, 0xe7, 0xca, 0xd8, 0xce, 0x8f, 0xd2, 0xee, 0x75, 0xb6, 0xfb,
	0x89, 0xe2, 0xcb, 0x30, 0x7c, 0x01, 0xba, 0x19, 0xcb, 0xc5, 0x2f, 0x1a, 0xa1, 0x47, 0x96, 0x6a,
	0xf7, 0x7d, 0xbd, 0xf8, 0x9d, 0x45, 0xd0, 0x07, 0x46, 0x6b, 0x68, 0xa4, 0x59, 0x9a, 0x6d, 0x4c,
	0xdf, 0x5d, 0x3d, 0xc4, 0x2b, 0x3e, 0x9f, 0x9a, 0xa0, 0xdf, 0x86, 0xc0, 0xef, 0xa0, 0x57, 0x5f,
	0x17, 0x75, 0x4a, 0xe0, 0xfb, 0xab, 0xc0, 0x05, 0x27, 0xb9, 0x57, 0x85, 0xe6, 0x82, 0xe5, 0xc4,
	0x6f, 0x10, 0xf0, 0x2d, 0x18, 0x06, 0xad, 0xce, 0x57, 0xb2, 0xe1, 0xe8, 0xb1, 0xa5, 0xd9, 0x7d,
	0xff, 0x42, 0x87, 0xaf, 0x80, 0x1e, 0x26, 0x98, 0xae, 0x38, 0xd2, 0x0b, 0x87, 0x37, 0x28, 0xb6,
	0xf0, 0x7f, 0x3f, 0xe9, 0x2c, 0x68, 0x2a, 0x7c, 0xd9, 0x83, 0xaf, 0xc1, 0x93, 0xb2, 0x3a, 0xf1,
	0xba, 0x25, 0xef, 0x4c, 0x85, 0x1f, 0xc1, 0x30, 0x25, 0x6b, 0x71, 0xba, 0xe7, 0x2c, 0x42, 0xbd,
	0x62, 0x7d, 0x67, 0xdc, 0x0b, 0x17, 0x74, 0x80, 0x51, 0x6a, 0x05, 0x6f, 0x16, 0xa1, 0xfe, 0x03,
	0xa1, 0xb6, 0xc1, 0xfb, 0xb6, 0x3d, 0x98, 0xea, 0xee, 0x60, 0xaa, 0x37, 0x07, 0x53, 0xfd, 0x7b,
	0x34, 0x95, 0xdd, 0xd1, 0x54, 0xfe, 0x1d, 0x4d, 0xe5, 0xe7, 0x34, 0xa6, 0x62, 0xf9, 0x27, 0x70,
	0x42, 0xb6, 0x72, 0x9b, 0xd5, 0xb9, 0xf7, 0x97, 0xe8, 0xae, 0xdd, 0xfa, 0x3d, 0x6d, 0x32, 0xc2,
	0x03, 0xbd, 0x7c, 0x4c, 0x1f, 0xee, 0x02, 0x00, 0x00, 0xff, 0xff, 0x75, 0xa5, 0xa8, 0xf2, 0xf9,
	0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NextClaimId.Size()
		i -= size
		if _, err := m.NextClaimId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.NextCollectionId.Size()
		i -= size
		if _, err := m.NextCollectionId.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if len(m.ClaimStoreKeys) > 0 {
		for iNdEx := len(m.ClaimStoreKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.ClaimStoreKeys[iNdEx])
			copy(dAtA[i:], m.ClaimStoreKeys[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.ClaimStoreKeys[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Claims) > 0 {
		for iNdEx := len(m.Claims) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.Claims[iNdEx].Size()
				i -= size
				if _, err := m.Claims[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.BalanceStoreKeys) > 0 {
		for iNdEx := len(m.BalanceStoreKeys) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.BalanceStoreKeys[iNdEx])
			copy(dAtA[i:], m.BalanceStoreKeys[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.BalanceStoreKeys[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Balances) > 0 {
		for iNdEx := len(m.Balances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Balances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Collections) > 0 {
		for iNdEx := len(m.Collections) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Collections[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PortId) > 0 {
		i -= len(m.PortId)
		copy(dAtA[i:], m.PortId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PortId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.PortId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.Collections) > 0 {
		for _, e := range m.Collections {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Balances) > 0 {
		for _, e := range m.Balances {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.BalanceStoreKeys) > 0 {
		for _, s := range m.BalanceStoreKeys {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Claims) > 0 {
		for _, e := range m.Claims {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClaimStoreKeys) > 0 {
		for _, s := range m.ClaimStoreKeys {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.NextCollectionId.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.NextClaimId.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PortId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PortId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collections", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Collections = append(m.Collections, &BadgeCollection{})
			if err := m.Collections[len(m.Collections)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Balances = append(m.Balances, &UserBalanceStore{})
			if err := m.Balances[len(m.Balances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalanceStoreKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BalanceStoreKeys = append(m.BalanceStoreKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Claims", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v Uint
			m.Claims = append(m.Claims, v)
			if err := m.Claims[len(m.Claims)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimStoreKeys", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimStoreKeys = append(m.ClaimStoreKeys, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextCollectionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextCollectionId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NextClaimId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NextClaimId.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
